apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
spec:
  selector:
    matchLabels:
      apps: postgresql
  template:
    metadata:
      labels:
        apps: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15.0-bullseye
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "kubenews"
            - name: POSTGRES_USER
              value: "kubenews"
            - name: POSTGRES_PASSWORD
              value: "Pg#123"
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    apps: postgresql
  ports:
    - port: 5432
      # targetPort: 5432
      # protocol: TCP
      # nodePort: 30001
  type: ClusterIP
  # type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      apps: web
  template:
    metadata:
      labels:
        apps: web
    spec:
      containers:
        - name: web
          image: rodrigocabral78/kube-news:v1
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "postgresql"
            - name: DB_DATABASE
              value: "kubenews"
            - name: DB_USERNAME
              value: "kubenews"
            - name: DB_PASSWORD
              value: "Pg#123"
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    apps: web
  ports:
    - port: 80
      targetPort: 8080
      # protocol: TCP
      nodePort: 30000
  # type: ClusterIP
  type: NodePort
---